/* ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
   btn-images.js — Button Image Customizer for Calc+
   Connect via: <script src="btn-images.js"></script>
   Requires: afterRender hook in main render() function
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ */

(function (global) {
  'use strict';

  /* ── Config ── */
  var STORAGE_KEY = 'calcpx4_btnimg';

  /* Buttons eligible for image overlay.
     act   → key used for storage & DOM lookup (data-act)
     btnId → element ID generated by main render() as "btn-{layout id}"
     lbl   → display label shown in the editor grid
     cls   → visual style class for editor cell */
  var ELIGIBLE = [
    { act: 'd7',      btnId: 'btn-d7',  lbl: '7', cls: 'bim-dig' },
    { act: 'd8',      btnId: 'btn-d8',  lbl: '8', cls: 'bim-dig' },
    { act: 'd9',      btnId: 'btn-d9',  lbl: '9', cls: 'bim-dig' },
    { act: 'div',     btnId: 'btn-div', lbl: '÷', cls: 'bim-op'  },
    { act: 'd4',      btnId: 'btn-d4',  lbl: '4', cls: 'bim-dig' },
    { act: 'd5',      btnId: 'btn-d5',  lbl: '5', cls: 'bim-dig' },
    { act: 'd6',      btnId: 'btn-d6',  lbl: '6', cls: 'bim-dig' },
    { act: 'mul',     btnId: 'btn-mul', lbl: '×', cls: 'bim-op'  },
    { act: 'd1',      btnId: 'btn-d1',  lbl: '1', cls: 'bim-dig' },
    { act: 'd2',      btnId: 'btn-d2',  lbl: '2', cls: 'bim-dig' },
    { act: 'd3',      btnId: 'btn-d3',  lbl: '3', cls: 'bim-dig' },
    { act: 'sub',     btnId: 'btn-sub', lbl: '−', cls: 'bim-op'  },
    { act: 'decimal', btnId: 'btn-dec', lbl: '.', cls: 'bim-dig' },
    { act: 'd0',      btnId: 'btn-d0',  lbl: '0', cls: 'bim-dig' },
    { act: 'add',     btnId: 'btn-add', lbl: '+', cls: 'bim-op'  },
  ];

  /* ── State ── */
  var images     = {};   /* { act: 'data:image/jpeg;base64,...' } */
  var currentAct = null; /* which button's image we're replacing  */
  var editorEl   = null; /* the overlay DOM node                  */
  var fileInput  = null; /* hidden <input type=file>              */

  /* ── Persistence ── */
  function load() {
    try { images = JSON.parse(localStorage.getItem(STORAGE_KEY) || '{}'); }
    catch (e) { images = {}; }
  }

  function save() {
    try { localStorage.setItem(STORAGE_KEY, JSON.stringify(images)); }
    catch (e) { console.warn('BtnImageMgr: storage full'); }
  }

  /* ── Image resize helper (canvas, max 200 px, JPEG 0.75) ── */
  function resizeAndStore(file, act, done) {
    var reader = new FileReader();
    reader.onload = function (ev) {
      var img = new Image();
      img.onload = function () {
        var max = 200;
        var ratio = Math.min(max / img.width, max / img.height, 1);
        var canvas = document.createElement('canvas');
        canvas.width  = Math.round(img.width  * ratio);
        canvas.height = Math.round(img.height * ratio);
        canvas.getContext('2d').drawImage(img, 0, 0, canvas.width, canvas.height);
        images[act] = canvas.toDataURL('image/jpeg', 0.75);
        save();
        done();
      };
      img.src = ev.target.result;
    };
    reader.readAsDataURL(file);
  }

  /* ── Apply images to live calculator buttons ── */
  function applyToCalc() {
    ELIGIBLE.forEach(function (e) {
      /* Try id first, then data-act fallback */
      var btn = document.getElementById(e.btnId)
             || document.querySelector('[data-act="' + e.act + '"]');
      if (!btn) return;

      /* Remove existing overlay */
      var old = btn.querySelector('.bim-overlay');
      if (old) old.remove();

      if (images[e.act]) {
        /* Ensure btn can clip the overlay */
        btn.style.position = 'relative';
        btn.style.overflow = 'hidden';

        var overlay = document.createElement('img');
        overlay.className = 'bim-overlay';
        overlay.src = images[e.act];
        overlay.style.cssText = [
          'position:absolute', 'inset:0', 'width:100%', 'height:100%',
          'object-fit:cover', 'border-radius:inherit',
          'pointer-events:none', 'z-index:2', 'display:block'
        ].join(';');
        btn.appendChild(overlay);

        /* Hide original text so image is the only content */
        btn.setAttribute('data-bim', '1');
      } else {
        btn.removeAttribute('data-bim');
      }
    });
  }

  /* ── CSS injected once ── */
  function injectCSS() {
    if (document.getElementById('bim-style')) return;
    var s = document.createElement('style');
    s.id = 'bim-style';
    s.textContent = [

      /* Overlay that covers a calculator button */
      '[data-bim="1"]{color:transparent!important;-webkit-text-fill-color:transparent!important}',

      /* ── Editor overlay ── */
      '.bim-bg{position:fixed;inset:0;z-index:9999;background:rgba(0,0,0,.65);',
        'display:flex;align-items:flex-end;justify-content:center;',
        'backdrop-filter:blur(8px);-webkit-backdrop-filter:blur(8px)}',

      '.bim-sheet{width:100%;max-width:480px;background:var(--face);',
        'border-radius:26px 26px 0 0;padding-bottom:env(safe-area-inset-bottom,20px);',
        'max-height:88vh;overflow-y:auto;box-shadow:0 -10px 40px rgba(0,0,0,.45);',
        'scrollbar-width:none}',
      '.bim-sheet::-webkit-scrollbar{display:none}',

      /* Header */
      '.bim-hdr{display:flex;align-items:center;justify-content:space-between;',
        'padding:18px 20px 12px;border-bottom:1px solid var(--sbrd)}',
      '.bim-ttl{font-family:"DM Sans",sans-serif;font-size:clamp(16px,5vw,19px);',
        'font-weight:700;color:var(--ink)}',
      '.bim-x{background:var(--ssec);border:none;width:30px;height:30px;',
        'border-radius:50%;cursor:pointer;font-size:16px;color:var(--ink-dim);',
        'display:flex;align-items:center;justify-content:center;flex-shrink:0}',

      /* Hint */
      '.bim-hint{padding:10px 20px 4px;font-family:"DM Sans",sans-serif;',
        'font-size:clamp(11px,3.5vw,13px);color:var(--ink-dim);line-height:1.5}',

      /* Button grid — mirrors calculator 4-col layout */
      '.bim-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;',
        'padding:14px 16px 24px}',

      /* Each cell */
      '.bim-cell{aspect-ratio:1;border-radius:18px;display:flex;',
        'flex-direction:column;align-items:center;justify-content:center;',
        'cursor:pointer;position:relative;border:2px solid transparent;',
        'transition:transform .15s,border-color .2s,box-shadow .2s;',
        'overflow:hidden;gap:3px}',
      '.bim-cell:active{transform:scale(.91)}',
      '.bim-dig{background:var(--ssec);box-shadow:0 3px 0 var(--sh-d),inset 0 1px 0 var(--sh-u)}',
      '.bim-op{background:linear-gradient(140deg,var(--pbg1),var(--pbg2));',
        'box-shadow:0 3px 0 var(--psh)}',
      '.bim-cell.bim-has{border-color:var(--acc);box-shadow:0 0 0 2px var(--acc)}',

      /* Label inside empty cell */
      '.bim-lbl{font-family:"DM Sans",sans-serif;font-size:clamp(20px,6.5vw,28px);',
        'font-weight:700;line-height:1;color:var(--ink);pointer-events:none}',
      '.bim-op .bim-lbl{color:var(--pink)}',
      '.bim-cam{font-size:clamp(11px,3.5vw,15px);pointer-events:none;',
        'color:var(--ink-dim);margin-top:1px}',
      '.bim-op .bim-cam{color:rgba(255,255,255,.6)}',

      /* Thumbnail when image is set */
      '.bim-thumb{width:100%;height:100%;object-fit:cover;display:block}',

      /* Remove button on thumbnail */
      '.bim-rm{position:absolute;top:4px;right:4px;width:22px;height:22px;',
        'border-radius:50%;background:rgba(200,30,30,.92);border:none;color:#fff;',
        'font-size:14px;font-weight:800;cursor:pointer;z-index:3;',
        'display:flex;align-items:center;justify-content:center;line-height:1;',
        'box-shadow:0 1px 4px rgba(0,0,0,.4)}',
      '.bim-rm:active{transform:scale(.88)}',

      /* "Clear all" row at bottom */
      '.bim-clr{margin:0 16px 16px;padding:12px;background:var(--ssec);',
        'border-radius:14px;text-align:center;cursor:pointer;',
        'font-family:"DM Sans",sans-serif;font-size:clamp(12px,4vw,15px);',
        'font-weight:600;color:var(--red);border:none;width:calc(100% - 32px)}',
      '.bim-clr:active{opacity:.7}',

    ].join('');
    document.head.appendChild(s);
  }

  /* ── Refresh the editor grid cells ── */
  function refreshGrid() {
    if (!editorEl) return;
    var grid = editorEl.querySelector('.bim-grid');
    if (!grid) return;
    grid.innerHTML = '';

    ELIGIBLE.forEach(function (e) {
      var cell = document.createElement('div');
      cell.className = 'bim-cell ' + e.cls + (images[e.act] ? ' bim-has' : '');

      if (images[e.act]) {
        /* Show thumbnail */
        var img = document.createElement('img');
        img.className = 'bim-thumb';
        img.src = images[e.act];
        cell.appendChild(img);

        /* Remove (×) button */
        var rm = document.createElement('button');
        rm.className = 'bim-rm';
        rm.textContent = '×';
        rm.title = 'Remove image';
        rm.addEventListener('click', function (ev) {
          ev.stopPropagation();
          delete images[e.act];
          save();
          applyToCalc();
          refreshGrid();
        });
        cell.appendChild(rm);
      } else {
        /* Show label + camera icon */
        var lbl = document.createElement('span');
        lbl.className = 'bim-lbl';
        lbl.textContent = e.lbl;
        cell.appendChild(lbl);

        var cam = document.createElement('span');
        cam.className = 'bim-cam';
        cam.textContent = '📷';
        cell.appendChild(cam);
      }

      /* Tap → pick image */
      cell.addEventListener('click', function () {
        currentAct = e.act;
        if (fileInput) fileInput.click();
      });

      grid.appendChild(cell);
    });
  }

  /* ── Build or show the editor overlay ── */
  function openEditor() {
    injectCSS();

    if (!fileInput) {
      fileInput = document.createElement('input');
      fileInput.type = 'file';
      fileInput.accept = 'image/*';
      fileInput.style.display = 'none';
      fileInput.addEventListener('change', function () {
        var file = fileInput.files[0];
        if (file && currentAct) {
          resizeAndStore(file, currentAct, function () {
            applyToCalc();
            refreshGrid();
          });
        }
        fileInput.value = '';
      });
      document.body.appendChild(fileInput);
    }

    if (!editorEl) {
      editorEl = document.createElement('div');
      editorEl.className = 'bim-bg';
      editorEl.innerHTML = [
        '<div class="bim-sheet">',
          '<div class="bim-hdr">',
            '<span class="bim-ttl">🖼️ Button Images</span>',
            '<button class="bim-x" id="bimCloseBtn" aria-label="Close">✕</button>',
          '</div>',
          '<p class="bim-hint">Tap any button to add a photo. The image replaces the button label in the calculator. Tap <b>×</b> on a thumbnail to remove it.</p>',
          '<div class="bim-grid"></div>',
          '<button class="bim-clr" id="bimClearAll">🗑 Clear All Button Images</button>',
        '</div>',
      ].join('');

      editorEl.querySelector('#bimCloseBtn').addEventListener('click', closeEditor);
      editorEl.querySelector('#bimClearAll').addEventListener('click', function () {
        if (!Object.keys(images).length) return;
        if (confirm('Remove all button images?')) {
          images = {};
          save();
          applyToCalc();
          refreshGrid();
        }
      });
      /* Tap backdrop → close */
      editorEl.addEventListener('click', function (ev) {
        if (ev.target === editorEl) closeEditor();
      });

      document.body.appendChild(editorEl);
    }

    refreshGrid();
    editorEl.style.display = 'flex';
    document.body.style.overflow = 'hidden';
  }

  function closeEditor() {
    if (editorEl) editorEl.style.display = 'none';
    document.body.style.overflow = '';
  }

  /* ── Public init — call once after DOM ready ── */
  function init() {
    load();
    /* Chain into afterRender so images reapply after every render() call */
    var prev = global.afterRender;
    global.afterRender = function () {
      if (typeof prev === 'function') prev();
      applyToCalc();
    };
    /* First apply on load */
    applyToCalc();
  }

  /* ── Expose API ── */
  global.BtnImageMgr = {
    init      : init,
    openEditor: openEditor,
    applyToCalc: applyToCalc,
  };

})(window);
